"$schema" = "schemas/schema.json"
[default]
description = """
This permission set configures which
sharesheet features are by default exposed.

#### Granted Permissions

It allows acccess to all sharesheet commands.

"""

permissions = [
  "allow-share-text",
  "allow-share-file",
]
